let A = parseFloat(prompt("Digite o primeiro numero"))
let B = parseFloat(prompt("Digite o segundo numero"))
let C = parseFloat(prompt("Digite o terceiro numero"))
let D = parseFloat(prompt("Digite o quarto numero"))

let soma1 = (A+B)
let soma2 = (A+C)
let soma3 = (A+D)
let soma4 = (B+C)
let soma5 = (B+D)
let soma6 = (C+D)

let multiplicacao1 = (A*B)
let multiplicacao2 = (A*C)
let multiplicacao3 = (A*D)
let multiplicacao4 = (B*C)
let multiplicacao5 = (B*D)
let multiplicacao6 = (C*D)

document.write ("Adições<br>")
document.write(A+" + "+B+" = "+soma1+".<br>")
document.write(A+" + "+C+" = "+soma2+".<br>")
document.write(A+" + "+D+" = "+soma3+".<br>")
document.write(B+" + "+C+" = "+soma4+".<br>")
document.write(B+" + "+D+" = "+soma5+".<br>")
document.write(C+" + "+D+" = "+soma6+".<br><br>")

document.write ("Multiplicações<br>")
document.write(A+" x "+B+" = "+multiplicacao1+".<br>")
document.write(A+" x "+C+" = "+multiplicacao2+".<br>")
document.write(A+" x "+D+" = "+multiplicacao3+".<br>")
document.write(B+" x "+C+" = "+multiplicacao4+".<br>")
document.write(B+" x "+D+" = "+multiplicacao5+".<br>")
document.write(C+" x "+D+" = "+multiplicacao6+".<br>")